packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.6.1'
  - '@storybook/addon-docs@10.6.1'
  - '@storybook/builder-vite@10.6.1'
  - '@storybook/html-vite@10.6.1'
  - '@storybook/html@10.6.1'
  - '@storybook/react-dom-shim@10.6.1'
  - storybook@10.6.1
  - '@playwright/test@1.63.0'
